version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
  open-pull-requests-limit: 2
  target-branch: overhaul-indev
  reviewers:
    - Redfire75369
  labels:
      - "Type: Dependabot"
  versioning-strategy: increase
