function init_game() {
	loadSave(JSON.parse(atob("eyJ2ZXJzaW9uIjp7ImFscGhhIjowLCJiZXRhIjo5fSwib3B0aW9ucyI6eyJub3RhdGlvbiI6IlNjaWVudGlmaWMiLCJub3RhdGlvbk5vIjowfSwibmF2aWdhdGlvbiI6eyJuYXZpVGFiIjoib3B0aW9ucyJ9LCJlbmVyZ3kiOiIxZSszMDgiLCJlZmYiOnsiYm91Z2h0IjowLCJjb3N0IjoiMTAwMCIsImNvc3RNdWx0IjoiMTAiLCJjb3N0TXVsdE11bHQiOiIxMCIsIm11bHQiOiIxIiwibXVsdE11bHQiOiIxLjEifSwicmVhY3RvciI6eyJhbW91bnQiOlsiMCIsIjAiLCIwIiwiMCIsIjAiLCIwIiwiMCIsIjAiXSwiY29zdCI6WyIxMCIsIjEwMCIsIjEwMDAwIiwiMTAwMDAwMCIsIjEwMDAwMDAwMDAiLCIxMDAwMDAwMDAwMDAwMCIsIjEwMDAwMDAwMDAwMDAwMDAwMDAiLCIxZSsyNCJdLCJjb3N0TXVsdCI6WyIxMDAwIiwiMTAwMDAiLCIxMDAwMDAiLCIxMDAwMDAwIiwiMTAwMDAwMDAwIiwiMTAwMDAwMDAwMDAiLCIxMDAwMDAwMDAwMDAwIiwiMTAwMDAwMDAwMDAwMDAwMCJdLCJib3VnaHQiOlswLDAsMCwwLDAsMCwwLDBdLCJtdWx0IjpbIjEiLCIxIiwiMSIsIjEiLCIxIiwiMSIsIjEiLCIxIl0sImNvc3RNdWx0TXVsdCI6IjEwIiwibXVsdE11bHQiOiIyIn0sIm1ldGVvciI6eyJzaG93ZXIiOjAsIm1ldGVvck11bHQiOiIyIiwidGltZSI6MTMuNTUwMDAwMDAwMDAwMDU4fSwibmFuaXRlcyI6eyJyZXNlYXJjaCI6MCwibmFuaXRlcyI6IjAiLCJuYW5pdGVVcGciOlsiIixmYWxzZV0sInRpbWUiOjEzLjU1MDAwMDAwMDAwMDA1OH0sInRpbWUiOjEzLjU1MDAwMDAwMDAwMDA1OCwibGFzdFVwZGF0ZSI6MTU4MTEzMjM2MTM5M30=")));
	document.getElementById("random").innerText = JSON.stringify(player);
	document.getElementById("production").style.display = "none";
	document.getElementById("nanite").style.display = "none";
	document.getElementById("options").style.display = "none";
	document.getElementById(player.navigation.naviTab).style.display = "inline-block";
	targetedNotationChange(player.options.notation);
}