name: Build Process
on:
  push:
    branches:
      - overhaul
      - overhaul-dev
      - overhaul-indev
  pull_request:
    branches:
      - overhaul
      - overhaul-dev
      - overhaul-indev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node 15
      uses: actions/setup-node@v2-beta
      with:
        node-version: 15.x

    - name: Install Dependencies
      run: npm ci

    - name: Run ESLint on Scripts
      run: npm exec --no eslint "javascripts/**/*.{js,jsx}" || true
    - name: Run Stylelint on Stylesheets
      run: npm exec --no stylelint "stylesheets/**/*.css" || true
    - name: Compile JSX with Babel
      run: npm exec --no -c "babel javascripts/react/dev --out-dir javascripts/react/dist"
